### ISSUE TITLE
Feature suggestion: Hotkey binding for toggling the mod on/off

### ISSUE THREAD

**Issue by BrunoDanUy** [Lortseam/no-weather-effects#1]
It is possible to turn the mod on and off by using Clothconfig and completeconfig, but you need to navigate the menus and find the specific mod in your mods list.

It would be nice to have a hotkey binding for this

**Comment by Lortseam** [comment]
Added in version 1.5.0.

**Comment by BrunoDanUy** [comment]
Amazing, Thank you!
